version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: movies-postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/postgresql/data
